apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{  .Chart.Name }}-configmap"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  MONGO_URL: "mongodb://169.57.206.164:27017/local"
  CONVERSATION_USERNAME: "YOUR_WATSON_CONVERSATION_USERNAME"
  CONVERSATION_PASSWORD: "YOUR_WATSON_CONVERSATION_PASSWORD"